version: '3'
services:
  db:
    build:
      context: ./build/db
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - .:/myappdo
    ports:
     - "5432:5432"
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "8080:40000"
    depends_on:
     - db
