version: '3'
services:
  db:
    build:
      context: ./build/db
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - .:/myappdo
    ports:
     - "5432:5432"
  web:
    build: .
    volumes:
      - .:/myapp
    command: shotgun -I /myapp app.rb -p 80 -o '0.0.0.0'
    ports:
      - "8080:80"
    #depends_on:
    #  - db
