version: '3'
services:
  db:
    image: postgres:alpine
  web:
    build: .
    command: ruby myapp.rb
    volumes:
      - .:/myapp
    ports:
      - "8080:8080"
    depends_on:
      - db
