development:
  adapter: postgresql
  encoding: unicode
  database: docker
  pool: 2
  username: docker
  password: docker
  host: db

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: docker
  pool: 2
  username: docker
  password: docker
  host: db
